-- Insert Demo Institutions
INSERT INTO institutions (name, city, state) VALUES
('Chalapathi Institute of Engineering and Technology', 'Guntur', 'Andhra Pradesh'),
('GMR Institute of Technology', 'Rajam', 'Andhra Pradesh'),
('Ajeenkya DY Patil University', 'Pune', 'Maharashtra'),
('Sanjay Ghodawat University', 'Kolhapur', 'Maharashtra'),
('Noida International University', 'Noida', 'Uttar Pradesh'),
('SMR University', 'Chennai', 'Tamil Nadu'),
('Sushant University', 'Gurugram', 'Haryana'),
('Visakha Institute of Engineering & Technology', 'Visakhapatnam', 'Andhra Pradesh'),
('PK DAS Institute of Social Sciences, Health Sciences & Technology', 'Palakkad', 'Kerala'),
('Lingaya’s Institute of Management and Technology', 'Vijayawada', 'Andhra Pradesh'),
('MVR College of Engineering and Technology', 'Paritala', 'Andhra Pradesh'),
('Bharath Institute of Higher Education and Research', 'Chennai', 'Tamil Nadu'),
('St. Peter’s Institute of Higher Education and Research (SPIHER)', 'Chennai', 'Tamil Nadu'),
('Lingaya’s Vidyapeeth', 'Faridabad', 'Haryana'),
('Sri Sri University', 'Cuttack', 'Odisha'),
('T.S Mishra University', 'Lucknow', 'Uttar Pradesh'),
('Subharti University', 'Meerut', 'Uttar Pradesh'),
('SNS College of Technology', 'Coimbatore', 'Tamil Nadu'),
('Chaitanya', 'Warangal', 'Telangana'),
('Geeta University', 'Panipat', 'Haryana'),
('S-VYASA University School of Advanced Studies', 'Bengaluru', 'Karnataka'),
('Yenepoya Bangalore', 'Bengaluru', 'Karnataka'),
('AMET University', 'Chennai', 'Tamil Nadu'),
('Yenepoya University', 'Mangalore', 'Karnataka'),
('Vivekananda Global University', 'Jaipur', 'Rajasthan'),
('B. S. Abdur Rahman Crescent Institute of Science & Technology', 'Chennai', 'Tamil Nadu'),
('Annamacharya University', 'Rajampet', 'Andhra Pradesh'),
('Sandip University', 'Nashik', 'Maharashtra'),
('Nadimpalli Satyanarayana Raju Institute of Technology (NSRIT)', 'Visakhapatnam', 'Andhra Pradesh'),
('Scope Global Skills University', 'Bhopal', 'Madhya Pradesh'),
('Alard University', 'Pune', 'Maharashtra'),
('Joy University', 'Kanyakumari', 'Tamil Nadu'),
('BEST Innovation University', 'Anantapur', 'Andhra Pradesh'),
('Takshashila University', 'Tindivanam', 'Tamil Nadu'),
('Chalapathi Institute of Technology', 'Guntur', 'Andhra Pradesh'),
('Sanskriti University', 'Mathura', 'Uttar Pradesh'),
('Aurora Deemed University', 'Hyderabad', 'Telangana');

-- Demo opportunities will be created dynamically or via API, but we can seed some
INSERT INTO opportunities (title, organization, category, description, eligibility, skills, deadline, location, mode, is_demo, verification_status) VALUES
('Demo AI Hackathon', 'Demo Organization', 'Hackathon', 'Build the next generation of AI apps in this 48-hour hackathon. Great prizes and mentorship available.', 'All students', ARRAY['Python', 'Machine Learning', 'GenAI'], timezone('utc', now()) + interval '10 days', 'Online', 'Online', true, 'verified'),
('Demo Web Development Internship', 'Tech Innovators', 'Internships', 'Join our core engineering team for a 3-month summer internship working on our modern web application.', '3rd and 4th year students', ARRAY['React', 'Next.js', 'TypeScript'], timezone('utc', now()) + interval '15 days', 'Remote', 'Online', true, 'verified'),
('Demo Engineering Scholarship', 'Future Builders Foundation', 'Scholarships', 'A merit-based scholarship for outstanding engineering students from tier-2 cities.', '1st and 2nd year students with >8.0 CGPA', ARRAY[]::text[], timezone('utc', now()) + interval '5 days', 'India', 'Online', true, 'verified'),
('Demo Coding Competition', 'CodeX', 'Competitions', 'Weekly algorithmic programming contest. Solve 4 problems in 2 hours.', 'Open to all', ARRAY['C++', 'Java', 'Python', 'Algorithms'], timezone('utc', now()) + interval '2 days', 'Online', 'Online', true, 'verified'),
('Demo GenAI Workshop', 'Google Developer Groups', 'Workshops', 'Learn how to build applications using the Gemini API in this hands-on workshop.', 'Open to all', ARRAY['JavaScript', 'API integration'], timezone('utc', now()) + interval '20 days', 'Bangalore', 'Hybrid', true, 'verified');
